# Prod Environment Settings
# Global settings
global:
  namespace: hertz-tuning-prod

# External Secrets settings
externalSecrets:
  secretStore:
    name: aws-ssm-store-prod
    region: ap-northeast-2
    path: 
      springboot: /global/k8s/springboot/prod